// Code generated by qtc from "page.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	"sumbur/views/static"
)

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

type HTML interface {
	Title() string
	StreamTitle(qw422016 *qt422016.Writer)
	WriteTitle(qq422016 qtio422016.Writer)
	Body() string
	StreamBody(qw422016 *qt422016.Writer)
	WriteBody(qq422016 qtio422016.Writer)
}

type BasePage struct{}

func (page *BasePage) StreamTitle(qw422016 *qt422016.Writer) {
	qw422016.N().S(`?`)
}

func (page *BasePage) WriteTitle(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	page.StreamTitle(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (page *BasePage) Title() string {
	qb422016 := qt422016.AcquireByteBuffer()
	page.WriteTitle(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (page *BasePage) StreamBody(qw422016 *qt422016.Writer) {
	qw422016.N().S(`?`)
}

func (page *BasePage) WriteBody(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	page.StreamBody(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (page *BasePage) Body() string {
	qb422016 := qt422016.AcquireByteBuffer()
	page.WriteBody(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func StreamPage(qw422016 *qt422016.Writer, page HTML) {
	qw422016.N().S(`<!DOCTYPE html>

<html lang="ru">


<head>

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="`)
	qw422016.E().S(static.Stamp("sumbur.css"))
	qw422016.N().S(`">

<title>`)
	page.StreamTitle(qw422016)
	qw422016.N().S(` — sumbur.su</title>

</head>


<body>

<div id="page">


<header>
Сумбур
</header>


<main>

<h1>`)
	page.StreamTitle(qw422016)
	qw422016.N().S(`</h1>

`)
	page.StreamBody(qw422016)
	qw422016.N().S(`

</main>


<footer>

<div>
© 2019–2025 Николай Новиков
</div>

<div>
<a href="mailto:sumbur@sumbur.su">sumbur@sumbur.su</a>
</div>

</footer>


</div>

</body>


</html>
`)
}

func WritePage(qq422016 qtio422016.Writer, page HTML) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamPage(qw422016, page)
	qt422016.ReleaseWriter(qw422016)
}

func Page(page HTML) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WritePage(qb422016, page)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
