// Code generated by qtc from "error_404.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package http_errors

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func (err *NotFound) StreamTitle(qw422016 *qt422016.Writer) {
	qw422016.N().S(`Ошибка 404`)
}

func (err *NotFound) WriteTitle(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	err.StreamTitle(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (err *NotFound) Title() string {
	qb422016 := qt422016.AcquireByteBuffer()
	err.WriteTitle(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (err *NotFound) StreamBody(qw422016 *qt422016.Writer) {
	qw422016.N().S(`Страница "`)
	qw422016.E().Z(err.path)
	qw422016.N().S(`" не найдена
`)
}

func (err *NotFound) WriteBody(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	err.StreamBody(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (err *NotFound) Body() string {
	qb422016 := qt422016.AcquireByteBuffer()
	err.WriteBody(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
